// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtC7NDa50yBTAWQI_6ZRXoMhbh0kkCr_I',
    appId: '1:362854248592:web:a5b3cd6d24274bf1e12815',
    messagingSenderId: '362854248592',
    projectId: 'simple-firebase-7f84b',
    authDomain: 'simple-firebase-7f84b.firebaseapp.com',
    storageBucket: 'simple-firebase-7f84b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBx8XhoK0NxFT6-9bVhDXfa_Nyb9Bsqjs',
    appId: '1:362854248592:android:b474a00cc6e09dd3e12815',
    messagingSenderId: '362854248592',
    projectId: 'simple-firebase-7f84b',
    storageBucket: 'simple-firebase-7f84b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX03hW1RvQPCr_ATY2SJg-j5vkTmIlrP8',
    appId: '1:362854248592:ios:1bea23dfc6cfb486e12815',
    messagingSenderId: '362854248592',
    projectId: 'simple-firebase-7f84b',
    storageBucket: 'simple-firebase-7f84b.firebasestorage.app',
    iosClientId: '362854248592-hj8pe1l3358jocdtresonu1nr9f2ijk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNoteManagementApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX03hW1RvQPCr_ATY2SJg-j5vkTmIlrP8',
    appId: '1:362854248592:ios:1bea23dfc6cfb486e12815',
    messagingSenderId: '362854248592',
    projectId: 'simple-firebase-7f84b',
    storageBucket: 'simple-firebase-7f84b.firebasestorage.app',
    iosClientId: '362854248592-hj8pe1l3358jocdtresonu1nr9f2ijk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNoteManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtC7NDa50yBTAWQI_6ZRXoMhbh0kkCr_I',
    appId: '1:362854248592:web:89d8ccb6284d8f47e12815',
    messagingSenderId: '362854248592',
    projectId: 'simple-firebase-7f84b',
    authDomain: 'simple-firebase-7f84b.firebaseapp.com',
    storageBucket: 'simple-firebase-7f84b.firebasestorage.app',
  );
}
